// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using asyncawait.Data;

namespace asyncawait.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20191108054333_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("asyncawait.Data.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("Areas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Area1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Area2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Area3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Area4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Area5"
                        });
                });

            modelBuilder.Entity("asyncawait.Data.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Company1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Company2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Company3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Company4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Company5"
                        });
                });

            modelBuilder.Entity("asyncawait.Data.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("Resources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Resource1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Resource2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Resource3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Resource4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Resource5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
